export class TestHelper {
    public static data = `[{
        "AangebodenSindsTekst": "24 april 2021",
        "AanmeldDatum": "/Date(1262300400000+0100)/",
        "AantalBeschikbaar": null,
        "AantalKamers": 4,
        "AantalKavels": null,
        "Aanvaarding": "InOverleg",
        "Adres": "Hendrik Soeteboomstraat 1",
        "Afstand": 0,
        "BronCode": "NVM",
        "ChildrenObjects": [
    
        ],
        "DatumAanvaarding": null,
        "DatumOndertekeningAkte": null,
        "Foto": "http://cloud.funda.nl/valentina_media/142/641/619_klein.jpg",
        "FotoLarge": "http://cloud.funda.nl/valentina_media/142/641/619_groot.jpg",
        "FotoLargest": "http://cloud.funda.nl/valentina_media/142/641/619_grotere.jpg",
        "FotoMedium": "http://cloud.funda.nl/valentina_media/142/641/619_middel.jpg",
        "FotoSecure": "http://cloud.funda.nl/valentina_media/142/641/619_klein.jpg",
        "GewijzigdDatum": null,
        "GlobalId": 5945253,
        "GroupByObjectType": "0fc72cce-b901-465b-a812-4f2420f14cd9",
        "Heeft360GradenFoto": true,
        "HeeftBrochure": false,
        "HeeftOpenhuizenTopper": false,
        "HeeftOverbruggingsgrarantie": false,
        "HeeftPlattegrond": true,
        "HeeftTophuis": false,
        "HeeftVeiling": false,
        "HeeftVideo": true,
        "HuurPrijsTot": null,
        "Huurprijs": null,
        "HuurprijsFormaat": null,
        "Id": "0fc72cce-b901-465b-a812-4f2420f14cd9",
        "InUnitsVanaf": null,
        "IndProjectObjectType": false,
        "IndTransactieMakelaarTonen": null,
        "IsSearchable": true,
        "IsVerhuurd": false,
        "IsVerkocht": false,
        "IsVerkochtOfVerhuurd": false,
        "Koopprijs": 500000,
        "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
        "KoopprijsTot": 500000,
        "Land": "Nederland",
        "MakelaarId": 24819,
        "MakelaarNaam": "Fransen & Kroes Makelaars",
        "MobileURL": "http://m.funda.nl/obj.aspx?goi=5945253",
        "Note": null,
        "OpenHuis": [
    
        ],
        "Oppervlakte": 0,
        "Perceeloppervlakte": 153,
        "Postcode": "1035NV",
        "Prijs": {
          "GeenExtraKosten": false,
          "HuurAbbreviation": "",
          "Huurprijs": null,
          "HuurprijsOpAanvraag": "",
          "HuurprijsTot": null,
          "KoopAbbreviation": "k.k.",
          "Koopprijs": 500000,
          "KoopprijsOpAanvraag": "",
          "KoopprijsTot": 500000,
          "OriginelePrijs": null,
          "VeilingText": ""
        },
        "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;500.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
        "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;500.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
        "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;500.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
        "Producten": [
          "Video",
          "Plattegrond",
          "360-fotos",
          "VirtueelOpenHuis"
        ],
        "Project": {
          "AantalKamersTotEnMet": null,
          "AantalKamersVan": null,
          "AantalKavels": null,
          "Adres": null,
          "FriendlyUrl": null,
          "GewijzigdDatum": null,
          "GlobalId": null,
          "HoofdFoto": "/img/thumbs/thumb-geen-foto.gif",
          "IndIpix": false,
          "IndPDF": false,
          "IndPlattegrond": false,
          "IndTop": false,
          "IndVideo": false,
          "InternalId": "00000000-0000-0000-0000-000000000000",
          "MaxWoonoppervlakte": null,
          "MinWoonoppervlakte": null,
          "Naam": null,
          "Omschrijving": null,
          "OpenHuizen": [
    
          ],
          "Plaats": null,
          "Prijs": null,
          "PrijsGeformatteerd": null,
          "PublicatieDatum": null,
          "Type": 0,
          "Woningtypen": null
        },
        "ProjectNaam": null,
        "PromoLabel": {
          "HasPromotionLabel": false,
          "PromotionPhotos": [
    
          ],
          "PromotionPhotosSecure": null,
          "PromotionType": 0,
          "RibbonColor": 0,
          "RibbonText": null,
          "Tagline": null
        },
        "PublicatieDatum": "/Date(1619215222000+0200)/",
        "PublicatieStatus": 0,
        "SavedDate": null,
        "Soort-aanbod": "woonhuis",
        "SoortAanbod": 10,
        "StartOplevering": null,
        "TimeAgoText": null,
        "TransactieAfmeldDatum": null,
        "TransactieMakelaarId": null,
        "TransactieMakelaarNaam": null,
        "TypeProject": 0,
        "URL": "http://www.funda.nl/koop/amsterdam/huis-41390616-hendrik-soeteboomstraat-1/",
        "VerkoopStatus": "StatusBeschikbaar",
        "WGS84_X": 4.895764,
        "WGS84_Y": 52.41786,
        "WoonOppervlakteTot": 74,
        "Woonoppervlakte": 74,
        "Woonplaats": "Amsterdam",
        "ZoekType": [
          10
        ]
      }]`
}
